(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
BeginPackage["ProcessWithExpACF`"];
RandomVariateExpACF::usage="RandomVariateExpACF[\!\(\*
StyleBox[\"dist\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"n\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\",\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\"\[CapitalDelta]t\",\nFontSlant->\"Italic\"]\),\!\(\*
StyleBox[\"\[Lambda]\",\nFontSlant->\"Italic\"]\),\!\(\*
StyleBox[\"x0\",\nFontSlant->\"Italic\"]\)] gives a list of \!\(\*
StyleBox[\"n\",\nFontSlant->\"Italic\"]\) pseudorandom variate process from the symbolic distribution \!\(\*
StyleBox[\"dist\",\nFontSlant->\"Italic\"]\), with exponential autocorrelation function with correlation time \!\(\*
StyleBox[\"\[Lambda]\",\nFontSlant->\"Italic\"]\), sample time \!\(\*
StyleBox[\"\[CapitalDelta]t\",\nFontSlant->\"Italic\"]\) and initial value \!\(\*
StyleBox[\"x0\",\nFontSlant->\"Italic\"]\)\!\(\*
StyleBox[\".\",\nFontSlant->\"Italic\"]\)"; 
Begin["`Private`"];
RandomVariateExpACF[dist_,n_,\[CapitalDelta]t_,\[Lambda]_,x0_]:=Module[{vals},
$Assumptions=x\[Element]Reals&&\[Lambda]>0&&\[Lambda]\[Element]Reals;
p=PDF[dist,x];
m=Mean[dist];K2=FullSimplify[-2 \[Lambda]/p  Integrate[(x-m)p,{x,-Infinity,x}]];(*(g^2)[x]*)
g[x_]=Sqrt[K2];
gg[x_]=FullSimplify[Sqrt[K2] D[Sqrt[K2],x]];
rnd=RandomVariate[NormalDistribution[],n-1];
f[y_,\[Xi]_]:=1/(1+\[Lambda] \[CapitalDelta]t) (y+ \[Lambda] m \[CapitalDelta]t+g[y]Sqrt[\[CapitalDelta]t]\[Xi]+1/2 gg[y]\[CapitalDelta]t(\[Xi]^2-1));
vals= FoldList[f,x0,rnd]
]
End[]
EndPackage[]
